export const SELECTED_SPANISH = 'SELECTED_SPANISH';
export const SELECTED_TSELTAL = 'SELECTED_TSELTAL';
export const START_PLAY = 'START_PLAY';
export const STOP_PLAY = 'STOP_PLAY';
export const ENABLE_PLAY = 'ENABLE_PLAY';
export const DISABLE_PLAY = 'DISABLE_PLAY'
export const PLAY_TOGGLE = 'PLAY_TOGGLE';
