export {
  WELCOME_SCREEN,
  LANGUAGE_SCREEN,
  SIDE_DRAWER,
  PARRILLA_SCREEN,
  ABOUT_SCREEN,
  NUMBERS_SCREEN,
  PLAY_BUTTON,
  SIDE_MENU_ID,
  MENU_BTN_ID,
  PLAY_BTN_ID,
  CENTER_STACK_ID,
  SIDE_DRAWER_ID,
  WELCOME_SCREEN_ID
} from './Screens';
export { pushInitialScreen} from './Navigation';
